---
- name: Installs unattended upgrades on a system.
  hosts: all
  gather_facts: false
  become: true
  tasks:
  
  - name: Installing unattended-upgrades
    ansible.builtin.apt:
      name: unattended-upgrades
      state: present
